import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '../components/Header';
import Layout from '../components/Layout';
import vercelLogo from '../public/vercel.svg';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Home Page</h1>
      <p>Home page content</p>
      <Image src={vercelLogo} alt="Vercel" />
    </Layout>
  );
}
