import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import { css } from '@emotion/react';
import pokemonDatabase from '../util/database';
import Link from 'next/link';

const containerStyles = css`
  display: flex;
  flex-wrap: wrap;
  gap: 3rem;
  justify-content: center;
  a {
    text-decoration: none;
    color: black;
  }
`;

const pokemonCardStyles = css`
  height: 350px;
  width: 250px;
  background-color: #1668c7;
  color: white;
  border: 2px solid black;
  border-radius: 8px;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  opacity: 0.8;
  :hover {
    box-shadow: rgb(85, 91, 255) 0px 0px 0px 3px,
      rgb(31, 193, 27) 0px 0px 0px 6px, rgb(255, 217, 19) 0px 0px 0px 9px,
      rgb(255, 156, 85) 0px 0px 0px 12px, rgb(255, 85, 85) 0px 0px 0px 15px;
    opacity: 1;
    transition: 0.3s ease-in-out;
  }
`;

const centerHeadingStyles = css`
  display: flex;
  justify-content: center;
  h1 {
    color: white;
  }
`;

const imageStyles = css`
  border-radius: 8px;
`;
const layoutStyles = css`
  margin: 1rem 1rem;
`;
export default function Home(props) {
  return (
    <Layout css={layoutStyles}>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div css={centerHeadingStyles}>
        {' '}
        <h1>Available Pokemon Cards</h1>
      </div>
      <div css={containerStyles}>
        {props.pokemonDatabase.map((product) => {
          return (
            <Link
              href={`/products/${product.id}`}
              key={'pokemon-' + product.id}
            >
              <a>
                <div css={pokemonCardStyles}>
                  <h2>{product.name}</h2>
                  <h4>{product.type}</h4>
                  <Image
                    css={imageStyles}
                    src={`/pokemon-images/${product.id}.jpeg`}
                    height="200%"
                    width="200%"
                    alt={product.name}
                  />
                </div>
              </a>
            </Link>
          );
        })}
      </div>
    </Layout>
  );
}
// Code in getserversideprops runs only in node js -> terminal console, you can read files from file system, connect to database
export function getServerSideProps() {
  return {
    props: { pokemonDatabase: pokemonDatabase },
  };
}
