import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import { css } from '@emotion/react';
import pokemonDatabase from '../util/database';
import Link from 'next/link';

const pokemonCardStyles = css`
  height: 350px;
  width: 300px;
  background-color: #297cdb;
  border: 2px solid black;
  border-radius: 8px;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const containerStyles = css`
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  justify-content: center;
  a {
    text-decoration: none;
    color: black;
  }
`;
const centerHeadingStyles = css`
  display: flex;
  justify-content: center;
`;

const imageStyles = css`
  border-radius: 8px;
`;

export default function Home(props) {
  return (
    <Layout>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div css={centerHeadingStyles}>
        {' '}
        <h1>Available Pokemon Cards</h1>
      </div>
      <div css={containerStyles}>
        {props.pokemonDatabase.map((product) => {
          return (
            <Link
              href={`/products/${product.id}`}
              key={'pokemon-' + product.id}
            >
              <a>
                <div css={pokemonCardStyles}>
                  <h2>{product.name}</h2>
                  <h4>{product.type}</h4>
                  <Image
                    css={imageStyles}
                    src={`/pokemon-images/${product.id}.jpeg`}
                    height="200%"
                    width="200%"
                    alt={product.name}
                  />
                </div>
              </a>
            </Link>
          );
        })}
      </div>
    </Layout>
  );
}
// Code in getserversideprops runs only in node js -> terminal console, you can read files from file system, connect to database
export function getServerSideProps() {
  return {
    props: { pokemonDatabase: pokemonDatabase },
  };
}
